To subtype
watir/watir pull request #531
Opened 2017-02-09 00:14 UTC by titusfortner

Removes support for `#siblings` since combining HTMLCollections seems like more trouble than it is worth. Doing it "correctly" would mean figuring out how to handle multiple selector signatures, etc, and if users really want it they can iterate over both the previous & next collections themselves.

Also uses `Element#to_subtype` to objects in `ElementCollection` in lieu of #521

2017-02-09 04:15 UTC, p0deje requested changes
Overall looks good:

1. There is a small comment I've left.
2. Let's add spec for getting collection of `elements` which return subtypes.

2017-02-09 04:15 UTC, p0deje commented on lib/watir/adjacent.rb
> +      klass = self.send(tag_name).class if tag_name
```ruby
if index
  klass = tag_name ? self.send(tag_name).class : HTMLElement
  klass.new(self, xpath: "./#{direction}#{tag_name || '*'}[#{index + 1}]")
else
  klass = tag_name ? Object.const_get("#{klass}Collection") : HTMLElementCollection
  klass.new(self, xpath: "./#{direction}#{tag_name || '*'}")
end
```

2017-02-10 21:37 UTC, titusfortner commented
The `adjacent_spec.rb` essentially already tests that functionality, but it makes sense to make it more explicit and add specs to `collection_spec.rb`.

2017-02-20 19:18 UTC, titusfortner commented
Merged - 7bd172cca9dbddb6d16a61016b8ac86218121d19 & 786fb126482495ef7aa2fd6453908c290430bd65

2017-02-20 19:18 UTC, closed without merging