allow location of elements using custom attributes
watir/watir pull request #687
Opened 2017-11-18 22:24 UTC by titusfortner

This is an example of how #681 can be addressed

Ideally people use HTML 5 compliant attributes, but I'm not sure there's a good reason to enforce that. This code would just record the presence of non compliant attributes and make note of it in the error message if it isn't found.

Creating methods is different. If they want to get the value of a non-compliant attribute, then they can do: `my_element.attribute_value('custom_attribute')` without providing support for `my_element.custom_attribute`.

2017-11-19 06:41 UTC, jkotests requested changes
`MissingWayOfFindingObjectException` no longer appears to be used. We should remove it from exceptions.rb.

2017-11-20 09:43 UTC, p0deje approved these changes

2017-11-20 17:44 UTC, titusfortner commented
Good call. Removed.

2017-11-20 17:52 UTC, jkotests approved these changes

2017-11-20 21:26 UTC, merged