add explicit support for Range inputs to `ElementCollection#[]`
watir/watir pull request #740
Opened 2018-05-29 18:08 UTC by titusfortner

Addresses #738

2018-05-29 18:50 UTC, jkotests requested changes

2018-05-29 18:50 UTC, jkotests commented on lib/watir/element_collection.rb
> +        value.map { |i| self[i] }
This won't work with negatives - eg `browser.divs[1..-1]`. I have used this type of Range before, so it would be nice to able to fix.

2018-05-29 19:23 UTC, titusfortner commented on lib/watir/element_collection.rb
> +        value.map { |i| self[i] }
I'm not following, we support [negative indexes](https://github.com/watir/watir/blob/master/spec/watirspec/elements/element_spec.rb#L309). Also, using `to_a` (e.g. , `divs.to_a[2..5]`) works with current code, we're just looking for a way to make it lazy loaded.

2018-05-29 19:31 UTC, titusfortner commented on lib/watir/element_collection.rb
> +        value.map { |i| self[i] }
Ah, ok, I see, the `Range` instance can't evaluate the negative number without knowing the length ahead of time. This means that it doesn't make sense for it to be lazy loaded.

2018-05-29 20:12 UTC, titusfortner commented
@jkotests this is now just sending it along to `#to_a` so that user's don't have to change their code. No lazy loading is allowed when using Ranges.

2018-05-30 01:33 UTC, jkotests approved these changes

2018-05-30 03:05 UTC, p0deje approved these changes

2018-05-31 04:10 UTC, merged