increase .flash speed and keep original bg-color of element
watir/watir pull request #747
Opened 2018-06-01 13:27 UTC by sjieg

PR https://github.com/watir/watir/pull/695 could not be updated anymore, so hereby the new PR.

I've also added specs that check if the bg-color is the same after flashing. Tested in chrome and ff.

2018-06-01 21:51 UTC, titusfortner reviewed
This flashes too quickly for me, but this was what the original watir-classic used, so I'm less against it.

What if we set it to 0.1 by default, and implemented: `element.flash :fast` (0.04sec) & `element.flash :slow` (0.2sec)?

2018-06-04 00:06 UTC, jkotests approved these changes
I don't notice a lot of difference between the delay times, so I'm fine with whatever you two agree on.

2018-06-05 12:48 UTC, sjieg commented
- Updated default `dalay: 0.1`
- Added possibility to allow multiple colors in 1 flash
- Added preset parameter
```
presets = {
          fast: { delay: 0.04 },
          slow: { delay: 0.2 },
          long: { flashes: 5, delay: 0.5 },
          rainbow: { flashes: 5, color: %w(red orange yellow green blue indigo violet) }
      }
return self.flash(presets[preset]) unless presets[preset].nil?
```
- Reworked how the flash loops to allow multiple colors.

I'm pretty sure this is not the best way to add presets, but this is my solution with my limited skills. Feedback is appreciated.
Let me know if the `:rainbow` preset is too much, I thought it was a nice _fun_ addition for TA'ers to talk about.

2018-06-07 00:10 UTC, titusfortner commented
This implementation looks solid to me. @jkotests can you double take on the new code?

2018-06-07 02:06 UTC, jkotests requested changes
Looks good, but I have some suggestions to make it easier to read.

2018-06-07 02:06 UTC, jkotests commented on lib/watir/js_execution.rb
> +        nextcolor = color[modulo]
While I think this works, it'd be easier to read as:

~~~~~~~~
(color * flashes).each do |nextcolor|
  element_call { execute_js(:backgroundColor, @element, nextcolor) }
  sleep(delay)
end
~~~~~~~~

2018-06-07 02:06 UTC, jkotests commented on lib/watir/js_execution.rb
> +      color.push(background_color)
You can avoid the conditional by doing:

~~~~~~~~
color = Array(color).push(background_color)
~~~~~~~~

2018-06-11 08:55 UTC, sjieg commented
Thanks for the feedback @jkotests! Always happy to learn more efficient notations.

2018-06-12 01:08 UTC, jkotests approved these changes

2018-07-07 17:55 UTC, merged