Add Element#obscured?
watir/watir pull request #804
Opened 2018-10-13 05:12 UTC by jkotests

Adds a method to check if an element is obscured - ie covered by another element. This allows users to check whether clicking an element will generate an ElementClickInterceptedError (or similar error based on driver).

This means that retrying clicks due to things like temporary overlays, can be changed from:

~~~~~~~~
begin
  browser.link.click
rescue
  retry
end
~~~~~~~~

To:

~~~~~~~~
browser.link.wait_while(&:obscured?).click
~~~~~~~~

2018-10-13 05:13 UTC, Rajagopalan-M commented
That's an amazing idea.

On Sat 13 Oct, 2018, 10:42 AM Justin Ko, <notifications@github.com> wrote:

> Adds a method to check if an element is obscured - ie covered by another
> element. This allows users to check whether clicking an element will
> generate an ElementClickInterceptedError (or similar error based on driver).
>
> This means that retrying clicks due to things like temporary overlays, can
> be changed from:
>
> begin
>   browser.link.click
> rescue
>   retry
> end
>
> To:
>
> browser.link.wait_while(&:obscured?).click
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/watir/watir/pull/804
> Commit Summary
>
>    - Add Element#obscured?
>
> File Changes
>
>    - *M* lib/watir/elements/element.rb
>    <https://github.com/watir/watir/pull/804/files#diff-0> (13)
>    - *A* lib/watir/js_snippets/elementObscured.js
>    <https://github.com/watir/watir/pull/804/files#diff-1> (14)
>    - *M* spec/watirspec/elements/element_spec.rb
>    <https://github.com/watir/watir/pull/804/files#diff-2> (36)
>    - *A* spec/watirspec/html/obscured.html
>    <https://github.com/watir/watir/pull/804/files#diff-3> (34)
>
> Patch Links:
>
>    - https://github.com/watir/watir/pull/804.patch
>    - https://github.com/watir/watir/pull/804.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/watir/watir/pull/804>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AeOm7nrJ8WNt9GXbdCtmWlu990eKwEj7ks5ukXYxgaJpZM4Xadcu>
> .
>

2018-10-13 05:37 UTC, Rajagopalan-M commented
But I want this behavior to be for all elements like waiting behavior for
visibility checking, stale element checking has done for all the action.

On Sat 13 Oct, 2018, 10:42 AM Justin Ko, <notifications@github.com> wrote:

> Adds a method to check if an element is obscured - ie covered by another
> element. This allows users to check whether clicking an element will
> generate an ElementClickInterceptedError (or similar error based on driver).
>
> This means that retrying clicks due to things like temporary overlays, can
> be changed from:
>
> begin
>   browser.link.click
> rescue
>   retry
> end
>
> To:
>
> browser.link.wait_while(&:obscured?).click
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/watir/watir/pull/804
> Commit Summary
>
>    - Add Element#obscured?
>
> File Changes
>
>    - *M* lib/watir/elements/element.rb
>    <https://github.com/watir/watir/pull/804/files#diff-0> (13)
>    - *A* lib/watir/js_snippets/elementObscured.js
>    <https://github.com/watir/watir/pull/804/files#diff-1> (14)
>    - *M* spec/watirspec/elements/element_spec.rb
>    <https://github.com/watir/watir/pull/804/files#diff-2> (36)
>    - *A* spec/watirspec/html/obscured.html
>    <https://github.com/watir/watir/pull/804/files#diff-3> (34)
>
> Patch Links:
>
>    - https://github.com/watir/watir/pull/804.patch
>    - https://github.com/watir/watir/pull/804.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/watir/watir/pull/804>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AeOm7nrJ8WNt9GXbdCtmWlu990eKwEj7ks5ukXYxgaJpZM4Xadcu>
> .
>

2018-10-13 17:19 UTC, titusfortner requested changes
This is great! Only caveat is that I'd like for us to test it on all the browsers before we merge it since it isn't a wire call and isn't a bang method. Looks like a couple are failing on Firefox on Travis. What have you run it on so far?

2018-10-13 17:25 UTC, titusfortner commented
It should be noted that this is likely to be a solid an alternate solution to #532 from #534.

@Rajagopalan-M yeah I would be in favor of it philosophically, but it would prevent users doing wheat @p0deje  is describing here: https://github.com/watir/watir/pull/534#issuecomment-283244188

The right answer is going to be getting the Watir::Executor working (eventually) so each user can pick and choose what gets added by default.

2018-10-13 17:39 UTC, Rajagopalan-M commented
Excited to see such a feature. But does that affect performance? Because we
can simply rescue as we are rescuing for other exception like
InvisibleElement, staleElement. What do you say? Firefox is giving standard
Error now ElementInterceptedError, likewise we can raise bug in chrome to
give standard error like Firefox is providing us. What do you say?

On Sat 13 Oct, 2018, 10:55 PM Titus, <notifications@github.com> wrote:

> It should be noted that this is likely to be a solid an alternate solution
> to #532 <https://github.com/watir/watir/issues/532> from #534
> <https://github.com/watir/watir/pull/534>.
>
> @Rajagopalan-M <https://github.com/Rajagopalan-M> yeah I would be in
> favor of it philosophically, but it would prevent users doing wheat
> @p0deje <https://github.com/p0deje> is describing here: #534 (comment)
> <https://github.com/watir/watir/pull/534#issuecomment-283244188>
>
> The right answer is going to be getting the Watir::Executor working
> (eventually) so each user can pick and choose what gets added by default.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/watir/watir/pull/804#issuecomment-429559838>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AeOm7n0loHGPsoimPMTcQJpAdlXAw8Aaks5ukiIngaJpZM4Xadcu>
> .
>

2018-10-13 17:48 UTC, titusfortner commented
By default Watir clicks the element and rescues exceptions and automatically deals with the results. It does not do that for element not clickable type exceptions.

Using `browser.link.wait_while(&:obscured?).click` will result in an extra `#execute_script` wire call before attempting to click the element. But it can also be used to do something like this (we'd have to find a way to test that this method actually rescues these exceptions to make sure this is true):

```ruby
def click_unobscured(element)
  element.click
rescue ElementNotInteractableError, ElementClickInterceptedError
  element. wait_while(&:obscured?).click
end
```

@jkotests do we know what exceptions this avoids? I'm not sure we've found a way to reliably reproduce either of these exceptions.

2018-10-13 17:56 UTC, Rajagopalan-M commented
That's the perfect way to solve!

On Sat 13 Oct, 2018, 11:18 PM Titus, <notifications@github.com> wrote:

> By default Watir clicks the element and rescues exceptions and
> automatically deals with the results. It does not do that for element not
> clickable type exceptions.
>
> Using browser.link.wait_while(&:obscured?).click will result in an extra
> #execute_script wire call before attempting to click the element. But it
> can also be used to do something like this (we'd have to find a way to test
> that this method actually rescues these exceptions to make sure this is
> true):
>
> def click_unobscured(element)
>   element.clickrescue ElementNotInteractableError, ElementClickInterceptedError
>   element. wait_while(&:obscured?).clickend
>
> @jkotests <https://github.com/jkotests> do we know what exceptions this
> avoids? I'm not sure we've found a way to reliably reproduce either of
> these exceptions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/watir/watir/pull/804#issuecomment-429561470>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AeOm7mYflpO_QznJe4_3Xtk4CazsPJQUks5ukidWgaJpZM4Xadcu>
> .
>

2018-10-13 19:43 UTC, jkotests commented
@titusfortner , I'll look into the test failures. The problem seems to be with #scroll_into_view and hidden elements, but I'm not exactly sure why.

I'm thinking I'll need to check that the element is present. Do you think it's better to have #obscured? wait for the element to be present (ie `element_call(:wait_for_present)`) or just do a check (ie `return true unless present?`)?

I'll have to do more testing to see what exceptions it avoids in Firefox. For Chrome, last I checked, it avoided Selenium::WebDriver::Error::UnknownError, which is Chrome's lack of specific ElementClickInterceptedError.

2018-10-13 19:49 UTC, titusfortner commented
yeah, it's a pain that Chrome is the only non-w3c compliant driver at this point.
Probably best to wait_for_present; I can't think of any use case that doesn't include wanting to click the element.
Do we get an error / handle the error if the element doesn't exist?

2018-10-14 03:06 UTC, Rajagopalan-M commented
@titusfortner @jkotests 

I have some other idea to handle this when it's chrome and that's what I have done in my local project. Please look at this code and let me know whether it's okay

>       rescue Selenium::WebDriver::Error::NoSuchWindowError
>         raise Exception::NoMatchingWindowFoundException, 'browser window was closed'
>       rescue =>e
>          if e.message.include? "Other element would receive the click"
>               retry            
>         end
>         raise_present unless Wait.timer.remaining_time.positive?
>      end

We can do this arrangement until Chrome releases standarad exception like FireFox(ElementClickInterceptedError)

What do you say?

2018-10-14 03:11 UTC, titusfortner commented
This PR should allow you to do the same thing more elegantly, but it still can't be rolled in as a default.

2018-10-14 05:20 UTC, p0deje approved these changes
I think there will be plenty of cases when this snippet will return incorrect results in future, but let's start with it. 👍

2018-10-14 05:21 UTC, p0deje commented
Please, keep in mind that will not prevent all the cases for using `rescue` because element might become unclickable between `obscured?` and `click` calls. But of course, the number of exception catching should drop.

2018-10-14 13:40 UTC, jkotests commented
I made the following changes to address the questions/concerns:
* `#obscured?` now requires the element to be present. The UnknownObjectException will be raised if it's hidden or does not exist. 
* Expanded the tests to also check that we are approximating what happens in the click - ie `#obscured?` should be true if `#click` will raise exception.

Tests passed locally using Chrome, Firefox and IE.

2018-10-14 14:56 UTC, jkotests commented
Great, the relaxed locate tests are failing. I'll take a look.

2018-10-14 22:15 UTC, jkotests commented
Can you remind me the history of relaxed_locate? If relaxed_locate is `false`, we don't do any waiting for `element_call`? For example, I'm calling `Element#wait_for_present`, which exits before the waiting:

~~~~~~~~
    def wait_for_present
      p = present?
      return p if !Watir.relaxed_locate? || p
~~~~~~~~

Should I be using a different method in `#obscured?` to wait for the element to be present? Or are tests that rely on `#wait_for_present` just not compliant with relaxed_locate = false?

2018-10-14 22:35 UTC, titusfortner commented
the `wait_for_*` methods should theoretically only be used for when taking actions on an element via `#element_call`.

The reason for the `#relaxed_locate` toggle was because some users were clicking on an element and using the resulting exception as part of their flow control. Essentially they were intentionally calling `#click` on an element that they expected not be present. Setting `Watir.relaxed_locate = false` is a way for each of those calls to not take an additional 30 seconds when they wanted to get the exception immediately.

All predicate methods on element: (`#exists?`, `#enabled?`, `#stale?`, `#present?`, `#visible?`) should immediately return a boolean value.

So we probably want something like:

```
def obscured?
    present? && element_call { execute_js(:obscured, @element) }
end
```

`element.wait_while(&:obscured?)` will poll until it goes away, and if the element might not be there in the first place, I think they should need to do: `element.wait_until(&:present?).wait_while(&:obscured?)` rather than us trying to figure out what that race condition might look like.

2018-10-14 22:36 UTC, titusfortner commented
Just noticed that `#focused?` really should be using `:assert_exist` in the `element_call` but that slipped through...

2018-10-15 12:59 UTC, jkotests commented
@titusfortner , the tests are passing now, except for on AppVeyor. That's a general problem we have right now, right?

2018-10-15 13:30 UTC, titusfortner approved these changes

2018-10-15 13:30 UTC, merged